# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10

before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  # example
  - xcodebuild clean build -project VerticalCardSwiper.xcodeproj -scheme Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # library
  - xcodebuild clean build -project VerticalCardSwiper.xcodeproj -scheme VerticalCardSwiper -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # UI Tests iPhone X
  - xcodebuild clean build test -project VerticalCardSwiper.xcodeproj -scheme UITests -sdk iphonesimulator12.0 -destination "platform=iOS Simulator,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # UI Tests iPhone SE
  - xcodebuild clean build test -project VerticalCardSwiper.xcodeproj -scheme UITests -sdk iphonesimulator12.0 -destination "platform=iOS Simulator,name=iPhone SE" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # UI Tests iPhone 8+
  - xcodebuild clean build test -project VerticalCardSwiper.xcodeproj -scheme UITests -sdk iphonesimulator12.0 -destination "platform=iOS Simulator,name=iPhone 8 Plus" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - pod lib lint